[package]
name = "volume_mixer_control"
version = "0.1.0"
authors = ["ericf"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
